### ISSUE TITLE
--win32 build process failure

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#1]
I installed a new/clean Ubuntu 16.04 64 bit VirtualBox VM and applied all available updates.
I then followed the instructions here to install and run docker-ce:

http://gnuarmeclipse.github.io/openocd/build-procedure/
https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/

I then installed prerequisites required by the GNU MCU Eclipse RISC-V GCC build script: curl, git, automake, patch, tar, unzip, zip

I then ran the following
```
git clone https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build.git ~/Downloads/riscv-none-gcc-build.git
date >> build.log; bash ~/Downloads/riscv-none-gcc-build.git/scripts/build.sh --win32 2>&1 | tee -a build.log; date >> build.log
```
However the build failed here:
```
riscv64-unknown-elf-gcc -dumpspecs > tmp-specs
/bin/sh: 1: riscv64-unknown-elf-gcc: not found
make[1]: *** [specs] Error 127
Makefile:1994: recipe for target 'specs' failed
make[1]: Leaving directory '/Host/Work/riscv-none-gcc/build/win32/gcc-first/gcc'
make: *** [all-gcc] Error 2
Makefile:4212: recipe for target 'all-gcc' failed
```
I'm attaching the build log and hopefully it's possible to pinpoint the problem from that.
If you need any more info please let me know.

Thanks.

[build.log.zip](https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build/files/1128731/build.log.zip)

**Comment by ilg-ul** [comment]
I guess the code to implicitly build the linux version has a problem.

try to explicitly build both --deb32 --win32.

**Comment by TommyMurphyTM1234** [comment]
Actually my original build that showed this failure was --deb32 --win32 and I thought that it might save some time reproducing the problem and capturing the log using just --win32 (however I guess not after all?).

So the problem will happen with --deb32 --win32 but I can run a build and capture the log anyway if you think it might help at all?

Thanks.

**Comment by ilg-ul** [comment]
I'm running a full build myself; up to now the --deb64 and --win32 chained correctly; let's see if the 32-bits version will also run as expected (probably tomorrow morning we'll know more).

**Comment by TommyMurphyTM1234** [comment]
I just tried running a new build using --deb32 --win32 but now I get this:
```
Running "inner-build.sh" script inside "riscv-none-gcc-debian32-build" container, image "ilegeul/debian32:9-gnu-mcu-eclipse"...
touch: cannot touch '/Host/Work/riscv-none-gcc/build/debian32/stamp_started': No such file or directory
```
The "/Host/" part of the path looks wrong.
In my case it should be "/home/user/"

Did this change break something?

https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build/commit/8e1f91d4920bdf83d466b68e9dfef7014f6fd57d

For now I just commented out the code that tries to create the "stamp_started" timestamp file.

**Comment by ilg-ul** [comment]
yes, sorry, I'm still working on the script and the current version is not consistent. :-(

I changed the default location of the build folder to be inside docker; this brings a big speed improvement on macOS, but in case the build fails, it will start from the beginning.

right now I'm running a build with --win32 only; if it is ok I'll publish the new version and let you know.

> The "/Host/" part of the path looks wrong.

the "/Host/" part of the path is correct inside Docker.

**Comment by TommyMurphyTM1234** [comment]
No worries - I just commented out the start timestamp bit for now.
I didn't realise that /Host was correct insider docker.
Thanks.

**Comment by ilg-ul** [comment]
> commented out the start timestamp

I'm afraid this is not enough, there are other changes too. :-(

**Comment by ilg-ul** [comment]
I pushed some commits, that shuld fix the --win32 problem; however It'll take a while to confirm it is ok.

**Comment by ilg-ul** [comment]
the script seems ok now for win32. the build is entirely in docker, no way to resume a failed build. during development, to store the build in your filesystem, use --develop.

I also added a page documenting the build: https://gnu-mcu-eclipse.github.io/toolchain/riscv/build-procedure/

there are other RISC-V related pages too, more or less ready.

**Comment by TommyMurphyTM1234** [comment]
Thanks a lot Liviu - much appreciated.
I'm trying out a new/clean build now.

**Comment by TommyMurphyTM1234** [comment]
Hi Liviu - I pulled the latest stuff after your previous post and did a --deb32 --win32 build but still got this:
```
Creating tgz archive...

/Host/Work/riscv-none-gcc/deploy /Host/Work/riscv-none-gcc/install/debian32/archive
SHA: 88b22f35ecbafa83ac6f812d222292d8188c2b42ae50d4e8b23737595e7c5ca8 ?gnu-mcu-eclipse-riscv-none-gcc-7.1.1-2-20170707-1006-debian32.tgz
/Host/Work/riscv-none-gcc/install/debian32/archive

Changing owner to non-root Linux user...
chown: cannot access '/Host/Work/riscv-none-gcc/build': No such file or directory
```
Any ideas?
Thanks.

**Comment by ilg-ul** [comment]
hmmm... that path is no longer valid, it should read something like `/tmp/build/...`.

my build will soon reach this point and I'll see what needs to be changed.

**Comment by ilg-ul** [comment]
I fixed it, that code is used only when the script is started on Linux, that's why it did not fail in my environment.

**Comment by TommyMurphyTM1234** [comment]
Thanks Liviu - I did a new --deb32 --win32 (maybe the explicit --deb32 is redundant here?) and after 8 hours it completed successfully. Thanks a lot. I'm assuming that it's OK for me to close this issue now.

**Comment by ilg-ul** [comment]
you're welcome!

just curious, why do you need to rebuild the toolchain?

**Comment by TommyMurphyTM1234** [comment]
Initially to figure out the link problem with _fini which you explained elsewhere. But then also because it looks like a better way to manage builds of the RISC-V tools compared to the less structured and more error prone way outlined on the riscv-gnu-toolchain github.

**Comment by ilg-ul** [comment]
> less structured and more error prone way outlined on the riscv-gnu-toolchain github.

ok, fully agree. I'm doing my best to advocate to SiFive for these new scripts, but for now they are still not convinced.

I guess it might help if you would advocate too, both on the public group and directly to SiFive.

I invite you to use this toolchain distribution intensively, and possibly recommend it to your users too.

**Comment by TommyMurphyTM1234** [comment]
Will do. Your docker approach is much better than the alternative in my opinion and experience.
