### ISSUE TITLE
GCC_TARGET reset after one set toolchains is built

### ISSUE THREAD

**Issue by AntonKrug** [gnu-mcu-eclipse/riscv-none-gcc-build#11]
I was trying to experiment with the newer toolchain and make it for time being as drop-in replacement of the previous one. Which means the older naming scheme. So normally the toolchain compiles just fine, but I wanted to override the values. So I made docker env file and set the values to this:

```bash
APP_LC_NAME=riscv64-unknown-elf-gcc
GCC_TARGET=riscv64-unknown-elf
```

Linux gcc compiled fine but then when:

```
`/Host/Work/riscv-none-gcc-7.2.0-4/install/centos64/archive/gnu-mcu-eclipse/riscv64-unknown-elf-gcc/7.2.0-4-20180619-1053/share' -> `/Host/Work/riscv-none-gcc-7.2.0-4/install/centos64/riscv64-unknown-elf-gcc/share'
SHA: 91f9d01121414ee96ac64b4340c0904bc92f82902dc8bf0e9ac118409d369606 ?gnu-mcu-eclipse-riscv64-unknown-elf-gcc-7.2.0-4-20180619-1053-centos64.tgz

Changing ownership to non-root Linux user...

Done.

Container script "/Host/Work/riscv-none-gcc-7.2.0-4/build.git/scripts/container-build.sh" completed at Tue Jun 19 14:06:58 UTC 2018.
Duration: 3 minutes.
Docker container "riscv-none-gcc-linux64-build" removed.
Mandatory GNU/Linux binaries missing
```

So I tried to troubleshoot it and noticed that the GCC_TARGET got reset to your default value in middle of the process. The Linux gets build with the GCC_TARGET I gave it to it, so that’s perfect, but then before building the Windows it tries to search for it and uses the previous value. So then I added echo in case the file is not found:

```bash
    if [ ! -f "${HOST_WORK_FOLDER_PATH}/install/${linux_distribution}64/${APP_LC_NAME}/bin/${GCC_TARGET}-gcc" ]
    then
      echo ${HOST_WORK_FOLDER_PATH} ${linux_distribution} ${APP_LC_NAME} ${GCC_TARGET}
      echo "Mandatory GNU/Linux binaries missing."
      exit 1
    fi
```

And even the GCC_TARGET=riscv64-unknown-elf was set previously correctly as the binaries have that name, the echo displayed the original default value anyway:

/home/akrug/Work/riscv-none-gcc-7.2.0-4 centos riscv-none-gcc **riscv-none-embed**

So again after while GCC_TARGET=**riscv-none-embed** even when for the linux compilation it was GCC_TARGET=**riscv64-unknown-elf**

I was compiling with --linux64 --win64 --env-file parameters.

Am I doing something wrong?

**Comment by ilg-ul** [comment]
Did you try a recursive grep for GCC_TARGET, to see where it is set?

**Comment by AntonKrug** [comment]
I will have to double check, but I think one place was the defs-source.sh ? I will probably undo all the mess I did in the meantime get back to you, when it's double checked.

**Comment by TommyMurphyTM1234** [comment]
> Did you try a recursive grep for GCC_TARGET, to see where it is set?

FWIW with the latest scripts GCC_TARGET is only set in one place:

```
./defs-source.sh
GCC_TARGET=${GCC_TARGET:-"riscv-none-embed"}
```

With the initialization allowing for it to be overridden externally, e.g. via an env file passed to build.sh via --env-file=<filename>.

I don't know if the issue reported above still persists with the latest scripts?

I've been using the latest scripts to build GCC 8.1.0 for --linux64 and --win64 without any problems.
