### ISSUE TITLE
Clarification needed: newlib and newlib nano code models

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#12]
There seems  to be conflicting information here:

https://gnu-mcu-eclipse.github.io/blog/2017/07/02/riscv-none-gcc-v7-1-1-1-20170702-released/#newlib-nano`

> The nano versions of the libraries are compiled with -Os -mcmodel=medlow, while the regular versions are compiled with -O2 -mcmodel=medany.

versus here:

https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build

> newlib-nano
> 
> The only notable addition is support for newlib-nano, using the --specs=nano.specs option. For better results, this option must be added to both compile and link time (the next release of the GNU MCU Eclipse plug-ins will add support for this).
> 
> If no syscalls are needed, --specs=nosys.specs can be used at link time to provide empty implementations for the POSIX system calls.
> 
> The libraries are compiled with -O2 -mcmodel=medany.

Is the first extract correct - i.e. newlib is compiled with -O2 -mcmodel=medany and newlib nano is compiled with -Os -mcmodel=medlow?

**Comment by ilg-ul** [comment]
the source code is always autoritative:

https://github.com/gnu-mcu-eclipse/riscv-none-gcc-build/blob/aebd76a09219630893013488d98a1b663e2197e7/scripts/container-build.sh#L271

the initial approach was to use medlow for nano, but it did not work.

**Comment by TommyMurphyTM1234** [comment]
Thanks Liviu.
Sorry, didn't think to check the build scripts.
