### ISSUE TITLE
Overriding default GCC_TARGET doesn't take effect globally?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#13]
scripts/defs-source.sh has:

`GCC_TARGET=${GCC_TARGET:-"riscv-none-embed"}`

I want the tools to use the legacy prefix riscv64-unknown-elf.
So I use an env file containing the following:

`GCC_TARGET=riscv64-unknown-elf`

and pass it to the build using --env-file test.env

The relevant folders/tools are renamed with the riscv64-unknown-elf prefix properly but I still get the following folder in the deployment archive:

`gnu-mcu-eclipse/riscv64-unknown-elf-gcc/8.1.0-2-20190114-1540/riscv-none-embed`

which seems to contain gdb python related support files:

```
riscv-none-embed
└───share                         
    └───gdb                       
        ├───python                
        │   └───gdb               
        │       ├───command       
        │       ├───function      
        │       └───printer       
        ├───syscalls              
        └───system-gdbinit        

```
Should that folder also have been named riscv64-unknown-elf?

If so then presumably this line in scripts/container-gcc-functions-source.sh needs to be modified to use ${GCC_TARGET} rather than the literal "riscv-none-embed" string?

`'--with-gdb-datadir='\''${prefix}'\''/riscv-none-embed/share/gdb' \`

If so then I'm a bit confused about how to do this because of the seemingly unusual quoting of this line...

Thanks a lot.

**Comment by TommyMurphyTM1234** [comment]
OK - changing this line in scripts/container-gcc-functions-source.sh:

`'--with-gdb-datadir='\''${prefix}'\''/riscv-none-embed/share/gdb'` \

to

`--with-gdb-datadir="${APP_PREFIX}/${GCC_TARGET}"/share/gdb` \

results in no riscv-none-embed folder and everything (including the directory tree snippet above) under riscv64-unknown-elf.

So assuming that this is the correct organization when overriding GCC_TARGET via an env file should I create a PR for this small change?

**Comment by ilg-ul** [comment]
The hard wired name is definitely a mistake.

As for the weird syntax... I completely forgot why that line uses so many apostrophes :-( It looks like a copy/paste from the ARM build scripts, which is also weird.

If you checked and your new version performs as expected, yes, please create the PR.

**Comment by TommyMurphyTM1234** [comment]
Yes - the modification that I made works and puts everything under riscv64-unknown-elf instead of leaving some bits under riscv-none-embed. I will create a PR for it tomorrow. Thanks.

**Comment by TommyMurphyTM1234** [comment]
Fixed by PR #14.

**Comment by ilg-ul** [comment]
I applied the same fix to the ARM build script, I hope everything is ok now.

I don't know if you noticed, in the latest version of the build scripts I took the same approach as ARM regarding a separate libexec folder, which is also the GNU default. Previously the libexec binaries were placed in the lib folder.

**Comment by ilg-ul** [comment]
BTW, do you have an update for the scripts to generate the latest SiFive binaries?

**Comment by TommyMurphyTM1234** [comment]
> I don't know if you noticed, in the latest version of the build scripts I took the same approach as ARM regarding a separate libexec folder, which is also the GNU default. Previously the libexec binaries were placed in the lib folder.

I didn't notice that - thanks for the heads up.

> BTW, do you have an update for the scripts to generate the latest SiFive binaries?

Not sure what you mean. Do you mean to pull stuff from the "best" places - e.g. upstream projects where applicable etc.?

**Comment by ilg-ul** [comment]
> Do you mean to pull stuff from the "best" places - e.g. upstream projects where applicable etc.?

I mean GCC 8.1.0, released by SiFive in December.

**Comment by TommyMurphyTM1234** [comment]
Sorry - I'm still confused. Your script is building 8.1. Is it a different 8.1 to SiFive's? Or is that the point - you/we don't know for sure what sources SiFive are building **their** 8.1 from?

**Comment by ilg-ul** [comment]
My latest build is v8.1.0-2-20181019, I guess the SiFive December release uses more recent sources.

SiFive uses their own fork of GCC, where they include patches for their devices, like attributes for their new interrupt controller. 

This makes building a generic RISC-V even more tricky.

So, if you want a more recent RISC-V GCC, that follows the SiFive release, please find out which commits to use and help me maintain the scripts.

**Comment by TommyMurphyTM1234** [comment]
OK - let me see what I can do on that front.

**Comment by ilg-ul** [comment]
From a user's perspective, it would be nice to have a release after each SiFive release.

However I don't have resources to do this, and without help I'll probably skip some releases. 

Compared to the messy RISC-V world, ARM has a more professional approach, they commited on two releases per year, and they always publish the sources used to build the entire toolchain, so rebuilding/repacking the toolchain is simple and safe.
