### ISSUE TITLE
--win32 and --win64 not working if env-file used to override APP_LC_NAME and/or GCC_TARGET

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#17]
I can't see that this is related to my recent changes (PR #14, PR #15, PR #16) but if I specify --win64 (or --windows64) when building it just builds the --linux64 tools and stops. No Windows 64 bit toolchain is built. I've looked at the regular build log and also with --debug enabled but so far I can't see what's wrong. Just logging it here to make others aware in case. I'll keep looking to see what's causing this.

**Comment by TommyMurphyTM1234** [comment]
Ah ...  RTFL(og)!

```
Changing ownership to non-root Linux user...

Done.

Container script "/Host/Work/riscv-none-gcc-8.1.0-2/build.git/scripts/container-build.sh" completed at Wed Jan 16 22:39:52 UTC 2019.

Duration: 76 minutes.

Docker container "riscv-none-gcc-linux64-build" removed.
Mandatory GNU/Linux binaries missing.
```

So for some reason after building the Linux 64 bit toolchain on which the Windows 64 bit tools build depends the check to verify that this toolchain exists fails for some reason. I can't see why immediately but will check...

**Comment by TommyMurphyTM1234** [comment]
OK - the check for the Linux 64 bit tools after building them for the Windows 64 build is:

```
    if [ ! -f "${HOST_WORK_FOLDER_PATH}/install/${linux_distribution}64/${APP_LC_NAME}/bin/${GCC_TARGET}-gcc" ]
    then
      echo "Mandatory GNU/Linux binaries missing."
      exit 1
    fi
```

But:

```
    echo "About to check for ... " 
    echo "${HOST_WORK_FOLDER_PATH}/install/${linux_distribution}64/${APP_LC_NAME}/bin/${GCC_TARGET}-gcc"
```

generates:

```
About to check for ... 
/home/user/Work/riscv-none-gcc-8.1.0-2/install/centos64/riscv-none-gcc/bin/riscv-none-embed-gcc
```

Even though I'm passing and env-file to the build and it includes:

```
APP_LC_NAME=riscv64-unknown-elf-gcc
GCC_TARGET=riscv64-unknown-elf
```

I think that the problem is that the env-file just gets passed on to Docker but the overridden values should also be used in the build script that runs on the native host?

I did not see this problem before because I was not using an env-file but was hacking defs-source.sh directly. 

So maybe it's a case of either (a) having build.sh use values defined in the env-file or (b) overriding some things (e.g. APP_LC_NAME and GCC_TARGET here) in two places - the env-file and the local environment?

**Comment by TommyMurphyTM1234** [comment]
So...

```
export LC_APP_NAME=riscv64-unknown-elf-gcc
export GCC_TARGET=riscv-unknown-elf
```

before calling build.sh works.

Maybe that's just the way it has to be done - set the env vars on the host before calling the bulld.sh script and pass the env file with the equivalent settings for the Docker container?

**Comment by ilg-ul** [comment]
> Maybe that's just the way it has to be done

maybe including the env file is missing, or is not done properly.

**Comment by TommyMurphyTM1234** [comment]
> maybe including the env file is missing, or is not done properly.

No the env file is definitely being passed correctly and taking effect in the docker(s) but the problem is that the build script running natively on the build host is using the original default values for variables defined in defs-source.sh. So as things stand, to override APP_LC_NAME and GCC_TARGET you need to specify the non default values twice - once in the build environment and again in the docker environment file.

**Comment by ilg-ul** [comment]
> the problem is that the build script running natively on the build host is using the original default values for variables defined in defs-source.sh

then my initial diagnostic stands; try to source the env file in the top script, right before sourcing `defs-source.sh`, preferably with an explanatory echo before.

**Comment by TommyMurphyTM1234** [comment]
OK - I tried that but since the technically the env-file is not a script but effectively an ini file (tag=value) it doesn't work due - for example - to spaces in GCC_MULTILIB list etc. To prevent problems with the native script would require quotes around the GCC_MULTILIB value but then the quotes are passed literally to the docker. So it would require more work/preprocessing to get something that works with both the native script and the docker (via the env file). I think I'm going to just accept this and set the two values above in the env file and in the build environment separately rather than to try to automate this.

**Comment by ilg-ul** [comment]
> technically the env-file is not a script but effectively an ini file (tag=value) 

[edit]

after some checking I discovered that the env file is passed separately to docker. you mean the syntax is not the same as that of shell and it cannot be included with source? 

is so, the scripts are partly wrong, since this same file is included with `source` in case docker is not used.

**Comment by TommyMurphyTM1234** [comment]
> you mean the syntax is not the same as that of shell and it cannot be included with source?

It is a simple tag=value format. 
E.g.

`GCC_MULTILIB=rv32i-ilp32-- rv32im-ilp32--`

For bash one would need:

`GCC_MULTILIB="rv32i-ilp32-- rv32im-ilp32--"`

but for docker an env file with that would pass the quotes literally which is wrong.
See the simple syntax rules here:

https://docs.docker.com/compose/env-file/

I see the env file being sourced in scripts/helper/host-functions-source.sh now.
This seems wrong alright.

**Comment by ilg-ul** [comment]
hmmm... it looks like there must be two different env files, one for native builds and one for docker. :-(

I guess the problem occurs only for the array used in GCC_MULTILIB, the other definitions do not includ spaces.

did you try to escape spaces with a backslash?

if this does not work, only explicitly filtering the quotes in docker seems to solve this.

what happened when you sourced the docker env file in the top bash? did bash throw an error on the GCC_MULTILIB? were the other definitions (like GCC_TARGET) ok?

**Comment by TommyMurphyTM1234** [comment]
The branding and multilib values both have spaces and caused an error when sourced into build.sh. I don't have the error to hand.

So it's not just the multilib list that is an issue here.

Escaping is no use. Even if it satisfies bash the escaping will be passed literally to docker as previously mentioned and that will be incorrect.

Looks like if env file settings need to be reused in the native scripts they might need some preprocessing to get them into a suitable format.

I'll have another look when I get a chance. I've reopened the issue for tracking purposes.

**Comment by TommyMurphyTM1234** [comment]
Just to clarify, reverting my recent changes to multilib list handling does nothing to address this issue. It was a latent problem regardless of the multilib list handling which only came to light coincidentally after I made those changes and started using the env file mechanism for overriding default values.

**Comment by ilg-ul** [comment]
I think that before a more elaborate solution is considered, we need to document this (in the README & source files), and suggest separate files for native vs docker use cases.

And possibly document the workaround of using explicit exports for APP_LC_NAME and/or GCC_TARGET.

**Comment by TommyMurphyTM1234** [comment]
Good points. I will look at writing a readme note when I get a chance.
