### ISSUE TITLE
Add rv32imafdc-ilp32d & rv64imafc-lp64f to multilibs

### ISSUE THREAD

**Issue by ilg-ul** [gnu-mcu-eclipse/riscv-none-gcc-build#18]
Based on Jim's suggestion:

https://github.com/riscv/riscv-gcc/issues/150#issuecomment-466174186

The new branch is:

https://github.com/sifive/riscv-gnu-toolchain/commit/31dffd24952c16a9bbc7d293fa6a5c152b5b43a6

The current SiFIve multilibs:

https://github.com/sifive/riscv-gnu-toolchain/blob/96ee91acbc24497b3c66b22f7e9aebf6060b0720/configure#L3314

**Comment by srey942** [comment]
Hi Liviu,

Can you please add rv64imafd-lp64d to this patch?
I am using your xPacks which uses this toolchain, it would be one-stop to have everything in one place.

Thanks
Sreyas

**Comment by ilg-ul** [comment]
I don't know what to say, for me the rv64imafd-lp64d doesn't make much sense, and I don't think we should bend the software to compensate for major design issues. Normally you should add c to your hardware and use the standard development tools.

**Comment by ilg-ul** [comment]
Fixed in 8.2.0-2.1.
