### ISSUE TITLE
Multilibs not built for all supported architectures/extensions?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#2]
Just noticed this and am logging it in case it helps.

According to this:

https://gnu-mcu-eclipse.github.io/blog/2017/07/02/riscv-none-gcc-v7-1-1-1-20170702-released/

> The supported architectures are:
> 
> rv32i[m][a][f[d]]
> rv32g
> rv64i[m][a][f[d]]
> rv64g

My interpretation of this is that the required multilibs for all possible combinations of architecture/extension above should be available.
Maybe that's not what is intended?

But if it is then the default list of multilibs here:

https://github.com/riscv/riscv-gcc/blob/riscv-gcc-7/gcc/config/riscv/t-elf-multilib

does not cover all possible combinations of architectures/extensions mentioned on the website - e.g. rv32imaf is not supported because the required multilibs are not built.

**Comment by ilg-ul** [comment]
> My interpretation of this is that the required multilibs for all possible combinations of architecture/extension above should be available.
> Maybe that's not what is intended?

it was intended to define the range of options for -march -mabi.

the list of multilibs is explicitly defined in the same page, and is identical to the official one provided in your link.

I'm not sure what is the issue you are raising, a documentation issue or a build issue. 

as for the build, I follow the official build, so if they extend the list, it'll automatically propagate to my release.

**Comment by ilg-ul** [comment]
fyi, I updated the page to explicitly refer to -march -mabi

**Comment by TommyMurphyTM1234** [comment]
Ok, for example rv32i[m][a][f[d]] encompasses rv32imaf but no such multilib is built.

**Comment by TommyMurphyTM1234** [comment]
Sorry - just saw the bit about the multilibs that are bundled. 
I'll mark this closed so.

**Comment by ilg-ul** [comment]
yes, probably there are many combinations left out. if you want more combinations, please ask the risc-v gcc maintainers to consider them.
