### ISSUE TITLE
Question: how to build additional multilibs?

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#3]
I want to add rv32imaf/ilp32f to the list of multilibs built.
So after I ran through one build of the tools using the GNU MCU Eclipse scripted docker approach I then went to ~/Work/riscv-none-gcc/riscv-none-gcc-20170612/gcc/config/riscv and executed:

`./multilib-generator rv32i-ilp32--c rv32im-ilp32--c rv32iac-ilp32-- rv32imac-ilp32-- rv32imafc-ilp32f-rv32imafdc- rv64imac-lp64-- rv64imafdc-lp64d-- rv32imaf-ilp32f-- > t-elf-multilib
`

giving this t-elf-multilib file to override the original default:

```
# This file was generated by multilib-generator with the command:
#  ./multilib-generator rv32i-ilp32--c rv32im-ilp32--c rv32iac-ilp32-- rv32imac-ilp32-- rv32imafc-ilp32f-rv32imafdc- rv64imac-lp64-- rv64imafdc-lp64d-- rv32imaf-ilp32f--
MULTILIB_OPTIONS = march=rv32i/march=rv32ic/march=rv32im/march=rv32imc/march=rv32iac/march=rv32imac/march=rv32imafc/march=rv32imafdc/march=rv32gc/march=rv64imac/march=rv64imafdc/march=rv64gc/march=rv32imaf mabi=ilp32/mabi=ilp32f/mabi=lp64/mabi=lp64d
MULTILIB_DIRNAMES = rv32i \
rv32ic \
rv32im \
rv32imc \
rv32iac \
rv32imac \
rv32imafc \
rv32imafdc \
rv32gc \
rv64imac \
rv64imafdc \
rv64gc \
rv32imaf ilp32 \
ilp32f \
lp64 \
lp64d
MULTILIB_REQUIRED = march=rv32i/mabi=ilp32 \
march=rv32im/mabi=ilp32 \
march=rv32iac/mabi=ilp32 \
march=rv32imac/mabi=ilp32 \
march=rv32imafc/mabi=ilp32f \
march=rv64imac/mabi=lp64 \
march=rv64imafdc/mabi=lp64d \
march=rv32imaf/mabi=ilp32f
MULTILIB_REUSE = march.rv32i/mabi.ilp32=march.rv32ic/mabi.ilp32 \
march.rv32im/mabi.ilp32=march.rv32imc/mabi.ilp32 \
march.rv32imafc/mabi.ilp32f=march.rv32imafdc/mabi.ilp32f \
march.rv32imafc/mabi.ilp32f=march.rv32gc/mabi.ilp32f \
march.rv64imafdc/mabi.lp64d=march.rv64gc/mabi.lp64d
```
However when I ran the scripted docker build again it did not  build the additional rv32imaf/ilp32f multilib and built the original list (i.e. excluding rv32imaf/ilp32f).

Note that doing the same thing with a "manual" build of the stuff from https://github.com/riscv/riscv-gnu-toolchain does build the additional rv32imaf/ilp32f multilib.

I know for sure that my non default t-elf-multilib file is not getting overwritten by a fresh download/extraction of the gcc sources and it remains in ~/Work/riscv-none-gcc/riscv-none-gcc-20170612/gcc/config/riscv after the build process has finished.

But perhaps changing it there does not mean that it gets seen by the docker container during the build process or something...?

Any idea on how to get the scripted docker build process to take cognizance of the updated t-elf-multilib?

Thanks a lot.

**Comment by ilg-ul** [comment]
> does not mean that it gets seen by the docker container

that's correct. 

that's exactly the point of using docker containers, they always produce the same results, regardless the external environment.

> how to get the scripted docker build process to take cognizance of the updated t-elf-multilib

if I remember right, the script uses several tarballs as inputs. if you prepare other such tarballs, and tell the script to get them from your location, the result will be different.

or you can modify the main script to run your own actions after extracting the tarballs.

**Comment by TommyMurphyTM1234** [comment]
Thanks Liviu. So I should...

1. Make the t-elf-multilib change
2. Make a tarball of my modified riscv-none-gcc folder
3. Host it somewhere 
4. Modify the build script to use that rather than the original riscv-none-gcc-20170112 tarball

And it should then build the additional lib?

Thanks a lot.

**Comment by ilg-ul** [comment]
> And it should then build the additional lib?

it sounds like a good plan.

although since you have to modify my script anyway, I'd also consider adding the code to make the multilib change in place, it might make the entire procedure simpler.

**Comment by ilg-ul** [comment]
and, in case you did not notice it yet, there is something like a `--develop` that switches the build folder from a docker internal folder to one mounted from the host. it is slower, but it allows to resume a crashed build, which might be useful during development.

**Comment by TommyMurphyTM1234** [comment]
Thanks Liviu - I'm playing with the script now. If I come up with anything that might be generally useful I'll let you know.

**Comment by ilg-ul** [comment]
sure, if you think that the rv32imaf/ilp32f pair is useful, we can add it to my script.

**Comment by TommyMurphyTM1234** [comment]
The whole issue of multilibs is a bit unclear to me to be honest - as I have posted here:

https://groups.google.com/a/groups.riscv.org/forum/?utm_medium=email&utm_source=footer#!topic/sw-dev/3PCI-Azaqfw

I presume that it would be difficult to arrive at a list that would satisfy all of the people all of the time.
On the other hand a toolchain that covered ALL possible multilibs might be useful assuming that the overheard (build time and installed size) was acceptable to those who only used one or a few of the possibilities.

Regarding my previous post I was more thinking of any improvements/generalisations that I might come up with that might be generally useful. On the other hand I guess that not everybody will want to build their own toolchain (using your approach or any other that works) especially as the RISC-V user base expands.

Anyway - if I have any bright ideas I'll let you know. :-)

**Comment by ilg-ul** [comment]
I tried to figure out these possibilities, but the list is huge, plus that I guess a good part of them will never be used, so I really don't know what to suggest.

I think that 1-2 more might be added, if really necessary, but the build time is already pretty long.

**Comment by TommyMurphyTM1234** [comment]
I have successfully modified the script to pull my own source tarballs with the riscv-gcc one containing a modified t-elf-multilib file that specifies the additional multilib that I want here (rv32imaf/ilp32f) and this works fine so I'll close this issue now as there is no problem per se with the script.

**Comment by ilg-ul** [comment]
how elaborate are the changes? how did you generate the list?

I guess, with some care, we can define some environment variables, and use the same script.

if the only change is the list of mulilibs, I guess I can build my toolchain with the extended list too.

fyi, I'll plan to use the xPack mechanism to also install binaries, including riscv-gcc and openocd; it might be useful for your distributions too.

**Comment by TommyMurphyTM1234** [comment]
In this case I just wanted a toolchain with the usual multilibs plus rv32imaf/ilp32f. But in the general case I might want any or all possible multilibs. I'm not sure that this would be a general or common requirement though?

**Comment by ilg-ul** [comment]
if you can think on how to generate the multilib file in the script, I can add it.

in practical terms I am thinking of an environment variable with the desired list; if present, it is used; if not, a default that includes the actual SiFive list plus the one you need is used.

with the above definition, the actual file is generated, then the build is started.

**Comment by ilg-ul** [comment]
I updated the script to take more environment input.

next time when I have some time, I'll add the code to use gits.

if you give me the code to generate the multilibs file, I'll add it too.

**Comment by ilg-ul** [comment]
I guess this issue was addressed by the latest script. do we still need it open?
