### ISSUE TITLE
Will tools work on RedHat 6?

### ISSUE THREAD

**Issue by evancox10** [gnu-mcu-eclipse/riscv-none-gcc-build#4]
Hi, I know that Debian 9 docker images are used to build these binaries. I'm confused how/if this will work when the computer I ultimately want to run the tools on is running Red Hat 6. For Linux, don't binaries generally need to be built on the distribution they will be used with, due to glibc symbol linkage issues? Debian 9 is relatively new (June 2017), and seems like it would its glibc would have newer symbols not present in my RHEL 6 distribution (November 2010).

**Comment by ilg-ul** [comment]
> Red Hat 6

hmmm... I'm afraid this is a bit too old.

the binaries generated by the script are intended for modern distributions.

**Comment by ilg-ul** [comment]
however, I think that with some small modifications, the script can be modified to run natively instead of using the docker image, similarly to the macOS build.

**Comment by evancox10** [comment]
My guess is that you will find a lot of corporate semiconductor/EDA users still on RHEL6. It's still in regular production support ([ends November 2020](https://access.redhat.com/support/policy/updates/errata)), and received a new point release just this year (March 2017). The simulation tools from our EDA vendor (starts with a C and rhymes with fence) only started supporting RHEL7 in the last year, and it takes time for IT to qualify and move to a new OS version. 

Also, many corporate users (including y.t.) will not have sudo privileges, so docker is a no go. When it comes to 3rd party software, our options are build from source and install the SW to the project directory, or use a portable binary. (Getting IT to install the tools globally is typically a non-starter.)

I'm not trying to put down the work here. We've had to work through building/installing/using the toolchain for our embedded environment and it's definitely a pain. I was looking forward to giving your toolchain a try, instead.

FYI, a quick google search led me to this as a possible solution for cross-distribution binary compatibility: https://phusion.github.io/holy-build-box/
It builds in clean-room CentOS 5 environment, and does some static linking of dependencies.

**Comment by ilg-ul** [comment]
I see. you made a good point.

and Holy Build Box seems an interesting solution. I'll consider it, but I can't commit on any date.

however, as an intermediate solution, I might modify the script to build natively on any linux.

**Comment by evancox10** [comment]
The option to build natively on the host Linux would be great. Let me know if you get around to this, I can give it a whirl on our systems.

**Comment by ilg-ul** [comment]
the current version now allows native builds, if no target plafrom is specified.

it works on my macOS.

however, trying to run it on Ubuntu 16 raised all kind of problems, like incompatible versions, so I have serious doubts that trying to fix them is worth the effort.

probably the Holy Build Box solution is more realistic.

**Comment by evancox10** [comment]
Thank you putting in the native build. When I have the time, I will try it out myself and see if I can work through any of the issues.

How would I replicate this?

**Comment by ilg-ul** [comment]
I don't know how you should configure your environment, probably incrementally, you start with a standard installation, try to run the script, it fails, you satisfy the new requirement, retry, and so on.

it would be great to document the process, to know exactly what packages were needed on your specific distribution.

however, please note that the OpenOCD build script was not very successful for native builds, it worked for Ubuntu since it is close to the Debian used in Docker, but when tried on ARCH it failed, the libraries are in different locations, and, what is worse, have multiple versions, and the script is not able to differentiate between them, so the created binaries were not functional.

**Comment by ilg-ul** [comment]
as for the Holy Build Box solution, it is extreme in the other direction, it uses Docker containers with a very old CentOS, and expects the developer to maintain derived containers with additional newer tools.

I guess it might work for GCC, but I don't have resources to experiment with it now.

**Comment by evancox10** [comment]
When I asked "How do I replicate", I just meant what commands do I issue to your scripts?

**Comment by ilg-ul** [comment]
if you start the script without any --xxx platform, it should do a native build.

to enable more tracing, use `DEBUG=-x bash script`.

**Comment by ilg-ul** [comment]
FYI, I'm currently migrating the build boxes from Debian 9 to CentOS 6. Initially I tried to go back to CentOS 5, but I faced several problems and had to dismiss it as too old;  however CentOS 6 seems fully functional; actually only the core is CentOS6, on top of it I installed the most actual tools.

@evancox10, does this answer your question?

**Comment by ilg-ul** [comment]
The binaries in the latest release were built on CentOS 6.

Please test them on your systems and let me know if we can close this issue.

**Comment by evancox10** [comment]
Hi Liviu,
Sorry for not getting to testing these. My tasks moved on to something else that I was very busy on, but that has just calmed down. I'll download the tools this week and give it a spin.

Thanks for your work porting the build to RHEL6!
