### ISSUE TITLE
--win32 build failed with latest build.sh

### ISSUE THREAD

**Issue by TommyMurphyTM1234** [gnu-mcu-eclipse/riscv-none-gcc-build#5]
Hi Liviu

I tried to do a build yesterday with the latest script on a Ubuntu 16.04 64 bit VM but it failed and I'm not sure what, if anything, that I did wrong or if it's a problem with the script or build process?

I was doing a --win32 build and it failed as per the the log output snippet below.
I understand that a --win32 build implicitly first does a --deb32/--linux32 build and this seems to have completed OK because the binary build tgz and sha files are in the ~/Work/riscv-none-gcc/deploy folder.
The failure seems to be because the --win32 build process cannot find the deb32 (or native?) riscv64-unknown-elf-gcc toolchain for some reason?

```
cp xgcc.exe gcc-cross.exe
i686-w64-mingw32-g++ -fno-PIE -c   -Wno-format-security -Wno-char-subscripts -Wno-deprecated -Wno-array-bounds -Wno-invalid-offsetof -pipe -ffunction-sections -fdata-sections -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -I. -Ic-family -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/c-family -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/../include -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/../libcpp/include -I/tmp/install/win32/include -I/tmp/install/win32/include -I/tmp/install/win32/include  -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/../libdecnumber -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/../libdecnumber/dpd -I../libdecnumber -I/Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/../libbacktrace -I/tmp/install/win32/include  -o c-family/cppspec.o -MT c-family/cppspec.o -MMD -MP -MF c-family/.deps/cppspec.TPo /Host/Work/riscv-none-gcc/riscv-none-gcc-7.1.1-2-20171017/gcc/c-family/cppspec.c
i686-w64-mingw32-g++ -no-pie   -Wno-format-security -Wno-char-subscripts -Wno-deprecated -Wno-array-bounds -Wno-invalid-offsetof -pipe -ffunction-sections -fdata-sections -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc -L/tmp/install/win32/lib -Wl,--gc-sections -Wl,--stack,12582912 -o cpp.exe gcc.o gcc-main.o ggc-none.o \
  c-family/cppspec.o  libcommon-target.a \
   libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a 
riscv64-unknown-elf-gcc -dumpspecs > tmp-specs
/bin/sh: 1: riscv64-unknown-elf-gcc: not found
make[1]: *** [specs] Error 127
Makefile:1994: recipe for target 'specs' failed
make[1]: Leaving directory '/tmp/build/win32/gcc-first/gcc'
make: *** [all-gcc] Error 2
Makefile:4212: recipe for target 'all-gcc' failed

```

I was just wondering what is the best way to diagnose this - e.g.

1. What log(s) can I look at from the failed build?

1. If I run a new build to see if it happens again should I add any other options (e.g. --develop?) to provide more detailed info and to leave the failed docker filesystem image behind for perusal?

1.  Any other tips?

Thanks a lot.

**Comment by ilg-ul** [comment]
hmmm... you are right.

I recently moved the install folder to a local Docker folder as well, so the windows build will no longer find the linux binaries, because they are lost between Docker invokations :-(

I'll probably have to copy the entire install folder to the shared one.

until then, as a workaround, try `--develop`, this should switch back to the shared folders.

**Comment by TommyMurphyTM1234** [comment]
Thanks Liviu - I'm trying a --develop --win32 build now to see how that goes and will post back when I have an update.

**Comment by ilg-ul** [comment]
I'm working on a fix to copy the install folder, but I'm experimenting on openocd, where the build cycle is shorter.

**Comment by ilg-ul** [comment]
the openocd build now leaves the install folder on the host.

I applied the same changes to the gcc build script, but... had no time to test it.

**Comment by TommyMurphyTM1234** [comment]
Thanks a lot.
Let me kick off a build in a while to try it.

**Comment by ilg-ul** [comment]
btw, how long does it take a build on your super-fast machine?

**Comment by TommyMurphyTM1234** [comment]
Unfortunately not much, if any, improvement on doing a build on my i7 laptop yet because the build is essentially sequential and not really parallelized yet. A --win32 build (which means --win32 and --deb32 - with default settings - e.g. including multilibs etc.) takes about 8 hours on both. We have some ideas of optimizing build times though but haven't yet been able to try them out yet... :-(

**Comment by ilg-ul** [comment]
yeah. it looks like the only thing we can do is trim our beards from time to time. if you don't have yours, you'll certainly get one while waiting for the builds...

now seriously, the build is awful, it does too many steps, inherited from the linux build, like the two step build, which might not be needed for our needs.

**Comment by TommyMurphyTM1234** [comment]
Just to confirm that my --win32 (which implicitly does --deb32) build completed successfully with the latest script and took 335 mins or ~ 5.5 hours on my i7/32GB HP EliteBook RAM 840 G3 using a Ubuntu 16.04 64 bit VirtualBox VM. Thanks a lot for the quick turnaround on that fix Liviu. We will hopefully be able to offer some suggestions on improving build parallelization/time soon.

**Comment by ilg-ul** [comment]
> build parallelization

I think that build parallelization should be fine _inside_ leaf make processes.

so, if you manage to **not** start multiple make processes in parallel, I guess you should be fine.
