### ISSUE TITLE
libnosys is missing leading underscores on symbol names

### ISSUE THREAD

**Issue by jstraus59** [gnu-mcu-eclipse/riscv-none-gcc-build#9]
The symbols in libnosys need leading underscores added in order to be compatible with the naming used in newlib. See discussion [here](https://forums.sifive.com/t/gnu-mcu-eclipse/659/16?u=jstraus) for details.

**Comment by ilg-ul** [comment]
please report this to the original RISC-V project, I'm currently not changing libnosys.

**Comment by jstraus59** [comment]
Will do. Sorry for the confusion - still learning my way around all the different repositories!

**Comment by ilg-ul** [comment]
no problem. please refer to my id in the new report, so I can track this too.
